#!/bin/bash

# Runs on Gentoo
if [ -a /etc/gentoo-release ]; then
	xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
	xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
	xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
	xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
	/home/chris/.scripts/helper\ scripts/clock.sh &
	feh --bg-fill ~/Pictures/Personal/GentooPape.png
	compton -b
	xscreensaver -no-splash &
	openbox
# Runs on Arch
else
	while true
		do
			BAR=$(/home/chris/.scripts/dwm/bar)
			xsetroot -name "$BAR"
			sleep 1s
		done &
	/home/chris/.scripts/dwm/startup
	dwm
fi
