#!/bin/bash

# Display the volume in i3bar and enable changing of volume with two-finger
# scrolling over the symbol and toggle mute with right click.

# Get the volume percentage:
VOLUME=$(amixer sget Master | egrep -o -m 1 "[0-9]+%")
RAW=$(echo $VOLUME | awk '{print substr($0, 0, length($0)-1)}')

# Check if muted:
STATE=`amixer sget Master | egrep -m 1 'Playback.*?\[o' | egrep -o '\[o.+\]'`

# What to display in i3bar:
if [[ $STATE == '[off]' ]]; then
        echo " Muted"
        echo ""
        echo "#F2777A"
        amixer -c 0 set IEC958,16 mute
        exit 0
elif [[ $RAW == 0 ]]; then
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#F2777A"
        amixer -c 0 set IEC958,16 mute
        exit 0 
elif [[ $RAW -lt 51 ]]; then
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#99CC99"
        amixer -c 0 set IEC958,16 mute
        exit 0
else
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#99CC99"
        amixer -c 0 set IEC958,16 mute
        exit 0
fi

