#!/bin/bash

# Display the volume in i3bar and enable changing of volume with two-finger
# scrolling over the symbol and toggle mute with right click.

# Get the volume percentage:
VOLUME=$(amixer sget Master | egrep -o -m 1 "[0-9]+%")
RAW=$(echo $VOLUME | awk '{print substr($0, 0, length($0)-1)}')

# Check if muted:
STATE=`amixer sget Master | egrep -m 1 'Playback.*?\[o' | egrep -o '\[o.+\]'`

# Use mouse to change volume and toggle mute in i3bar:
case $BLOCK_BUTTON in
  # Right click to toggle mute
  3) amixer -q sset Master toggle & ~/.i3/vol-notify ;;
  # Scroll up to increase volume
  4) amixer -q sset Master 5%+ & ~/.i3/vol-notify ;;
  # Scroll down to decrease volume
  5) amixer -q sset Master 5%- & bash ~/.i3/vol-notify ;;
esac

# What to display in i3bar:
if [[ $STATE == '[off]' ]]; then
        echo " Muted"
        echo ""
        echo "#F2777A"
        exit 0
elif [[ $RAW == 0 ]]; then
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#F2777A"
        exit 0 
elif [[ $RAW -lt 51 ]]; then
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#99CC99"
        exit 0
else
        echo "" $VOLUME
        echo "" $VOLUME
        echo "#99CC99"
        exit 0
fi
